# Generated by Django 2.1.3 on 2018-12-04 22:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('problem_type', models.CharField(choices=[('Integrate', 'Integrate'), ('Prime factoring', 'Prime factoring')], max_length=256)),
                ('argument', django.contrib.postgres.fields.jsonb.JSONField(max_length=256)),
            ],
        ),
    ]
